package com.groupdocs.examples.metadata;

import java.nio.file.Path;

import static com.groupdocs.examples.metadata.utils.FilesUtils.makeFilesPath;

public interface SampleFiles {
    Path INPUT_FILES_DIRECTORY = makeFilesPath("");
    Path INPUT_DOCX = makeFilesPath("input.docx");
    Path INPUT_DOC = makeFilesPath("input.doc");
    Path INPUT_XLSX = makeFilesPath("input.xlsx");
    Path INPUT_PPTX = makeFilesPath("input.pptx");
    Path INPUT_VSDX = makeFilesPath("input.vsdx");
    Path INPUT_PDF = makeFilesPath("input.pdf");
    Path PDF_JSON = makeFilesPath("pdf.json");
    Path JPEG_WITH_XMP = makeFilesPath("xmp.jpg");
    Path INPUT_ONE = makeFilesPath("input.one");
    Path PROTECTED_DOCX = makeFilesPath("protected.docx");
    Path INPUT_RAR = makeFilesPath("input.rar");
    Path INPUT_7Z = makeFilesPath("input.7z");
    Path INPUT_TAR = makeFilesPath("input.tar");
    Path INPUT_ZIP = makeFilesPath("input.zip");
    Path INPUT_WITH_APE_MP3 = makeFilesPath("ape.mp3");
    Path INPUT_WITH_ID3V1_MP3 = makeFilesPath("id3v1.mp3");
    Path INPUT_WITH_ID3V2_MP3 = makeFilesPath("id3v2.mp3");
    Path INPUT_WITH_LYRICS_MP3 = makeFilesPath("lyrics.mp3");
    Path INPUT_WAV = makeFilesPath("input.wav");
    Path INPUT_VCF = makeFilesPath("input.vcf");
    Path INPUT_DXF = makeFilesPath("input.dxf");
    Path INPUT_VDX = makeFilesPath("input.vdx");
    Path INPUT_SIGNED_PDF = makeFilesPath("signed.pdf");
    Path INPUT_PPT = makeFilesPath("input.ppt");
    Path INPUT_MPP = makeFilesPath("input.mpp");
    Path INPUT_XLS = makeFilesPath("input.xls");
    Path INPUT_EPUB = makeFilesPath("input.epub");
    Path INPUT_EML = makeFilesPath("input.eml");
    Path INPUT_MSG = makeFilesPath("input.msg");
    Path INPUT_TTF = makeFilesPath("input.ttf");
    Path INPUT_BMP = makeFilesPath("input.bmp");
    Path INPUT_DICOM = makeFilesPath("input.dicom");
    Path INPUT_DNG = makeFilesPath("input.dng");
    Path INPUT_GIF = makeFilesPath("input.gif");
    Path CANON_JPEG = makeFilesPath("canon_raw.jpg");
    Path NIKON_JPEG = makeFilesPath("nikon_raw.jpg");
    Path PANASONIC_JPEG = makeFilesPath("panasonic_raw.jpg");
    Path SONY_JPEG = makeFilesPath("sony_raw.JPG");
    Path INPUT_WITH_BARCODES_JPEG = makeFilesPath("barcode.jpg");
    Path INPUT_WITH_IRB_JPEG = makeFilesPath("irb.jpg");
    Path INPUT_JP2 = makeFilesPath("input.jp2");
    Path INPUT_PNG = makeFilesPath("input.png");
    Path EXIF_PSD = makeFilesPath("exif.psd");
    Path IRB_PSD = makeFilesPath("irb.psd");
    Path IPTC_PSD = makeFilesPath("iptc.psd");
    Path INPUT_CR2 = makeFilesPath("input.CR2");
    Path IPTC_TIFF = makeFilesPath("iptc.tiff");
    Path INPUT_TORRENT = makeFilesPath("input.torrent");
    Path INPUT_ASF = makeFilesPath("input.asf");
    Path INPUT_AVI = makeFilesPath("input.avi");
    Path INPUT_FLV = makeFilesPath("input.flv");
    Path INPUT_MKV = makeFilesPath("input.mkv");
    Path SUBTITLES_MKV = makeFilesPath("subtitles.mkv");
    Path INPUT_MOV = makeFilesPath("input.mov");
    Path INPUT_JPG = makeFilesPath("input.jpg");
    Path EXIF_TIFF = makeFilesPath("exif.tiff");
    Path EXIF_JPEG = makeFilesPath("exif.jpg");
    Path IPTC_JPEG = makeFilesPath("iptc.jpg");
    Path XMP_PNG = makeFilesPath("xmp.png");
    Path XMP_JPG = makeFilesPath("xmp.jpg");
    Path XMP_GIF = makeFilesPath("xmp.gif");
}
